export const MY_UPCOMING_ACTIVITIES = [
  {
    id: "ua1",
    title: "Morning Walk with Sarah",
    description: "Light walk to start the weekend and catch up with Sarah.",
    date: "Sat, Nov 16",
    time: "8:00 AM",
    location: "English Garden",
    hostType: "friend",
    hostId: "f3",
    hostName: "Sarah",
    visibility: "friends",
    maxParticipants: 4,
    status: "confirmed",
  },
  {
    id: "ua2",
    title: "Deep Work Sprint",
    description: "Heads-down focus block with a small accountability group.",
    date: "Mon, Nov 18",
    time: "9:30 AM",
    location: "Home office",
    hostType: "self",
    hostId: "f0",
    hostName: "Wei (You)",
    visibility: "friends",
    maxParticipants: 3,
    status: "pending",
    requests: [
      {
        id: "req-seed-1",
        requesterId: "f1",
        requesterName: "Hans",
        status: "pending",
        type: "join",
      },
    ],
  },
  {
    id: "ua3",
    title: "Reading & Tea",
    description: "Slow evening read with herbal tea to wind down.",
    date: "Wed, Nov 20",
    time: "7:00 PM",
    location: "Home",
    hostType: "self",
    hostId: "f0",
    hostName: "Wei (You)",
    visibility: "friends",
    maxParticipants: 2,
    status: "confirmed",
  },
];

export const FRIEND_SHARED_ACTIVITIES = [
  {
    id: "fa1",
    title: "Silent Co-working",
    description: "Thomas is hosting a silent focus room. Drop in anytime.",
    date: "Today",
    time: "4:00 PM",
    location: "Virtual room",
    hostType: "friend",
    hostId: "f2",
    hostName: "Thomas",
    visibility: "friends",
    status: "confirmed",
  },
  {
    id: "fa2",
    title: "Evening Walk",
    description: "Hans is doing a 30-minute stroll. Fresh air welcome.",
    date: "Today",
    time: "7:30 PM",
    location: "Isar river trail",
    hostType: "friend",
    hostId: "f1",
    hostName: "Hans",
    visibility: "friends",
    status: "confirmed",
  },
];

export const PUBLIC_EVENTS = [
  {
    id: "pe1",
    title: "Guided Breathwork",
    description: "Community-led 15 minute reset with light stretching.",
    date: "Tomorrow",
    time: "12:00 PM",
    location: "Virtual",
    hostType: "public",
    hostId: "org-1",
    hostName: "Community Center",
    visibility: "public",
    maxParticipants: 30,
    status: "confirmed",
  },
  {
    id: "pe2",
    title: "Screen-free Social",
    description: "Offline evening with board games and tea.",
    date: "Fri, Nov 22",
    time: "7:00 PM",
    location: "Local library",
    hostType: "public",
    hostId: "org-2",
    hostName: "Neighborhood Hub",
    visibility: "public",
    maxParticipants: 12,
    status: "confirmed",
  },
];

export const INCOMING_REQUESTS = [
  {
    id: "req-host-1",
    activityId: "ua2",
    activityTitle: "Deep Work Sprint",
    requesterId: "f1",
    requesterName: "Hans",
    hostId: "f0",
    status: "pending",
    visibility: "friends",
  },
];

